create table public.telegram_recruitments (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  message_id bigint,
  created_by bigint not null,
  scheduled_date date not null,
  hour smallint not null check (hour between 1 and 24),
  target_count smallint not null default 10 check (target_count > 0),
  status text not null default 'open' check (status in ('open', 'full', 'expired', 'failed')),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  created_at timestamptz not null default now()
);

create unique index telegram_recruitments_one_time_per_chat
  on public.telegram_recruitments (chat_id, scheduled_date, hour)
  where status in ('open', 'full');
create index telegram_recruitments_expires_at_idx
  on public.telegram_recruitments (expires_at)
  where status in ('open', 'full');

create table public.telegram_recruitment_votes (
  recruitment_id bigint not null references public.telegram_recruitments(id) on delete cascade,
  telegram_user_id bigint not null,
  display_name text not null,
  username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (recruitment_id, telegram_user_id)
);

create index telegram_recruitment_votes_created_idx
  on public.telegram_recruitment_votes (recruitment_id, created_at);

create table public.telegram_updates (
  update_id bigint primary key,
  processed_at timestamptz not null default now()
);

alter table public.telegram_recruitments enable row level security;
alter table public.telegram_recruitment_votes enable row level security;
alter table public.telegram_updates enable row level security;
revoke all on table public.telegram_recruitments, public.telegram_recruitment_votes, public.telegram_updates from public, anon, authenticated;
grant select, insert, update, delete on table public.telegram_recruitments, public.telegram_recruitment_votes, public.telegram_updates to service_role;
grant usage, select on sequence public.telegram_recruitments_id_seq to service_role;
