create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index audit_logs_created_at_idx on public.audit_logs (created_at desc);

alter table public.audit_logs enable row level security;
revoke all on table public.audit_logs from anon, authenticated;
grant select, insert, delete on table public.audit_logs to service_role;
grant usage, select on sequence public.audit_logs_id_seq to service_role;

create or replace function public.set_player_tiers(changes jsonb, p_actor_id uuid)
returns integer
language plpgsql
set search_path = ''
as $$
declare
  before_values jsonb;
  after_values jsonb;
  updated_count integer;
begin
  select coalesce(jsonb_agg(jsonb_build_object(
    'playerId', player.id,
    'nickname', player.nickname,
    'tier', player.tier,
    'order', player.tier_order
  ) order by player.id), '[]'::jsonb)
  into before_values
  from public.players as player
  join jsonb_array_elements(changes) as change(value)
    on player.id = (change.value ->> 'playerId')::bigint;

  if jsonb_array_length(before_values) <> jsonb_array_length(changes) then
    raise exception 'player ranking update count mismatch';
  end if;

  update public.players as player
  set
    tier = (change.value ->> 'tier')::smallint,
    tier_order = (change.value ->> 'order')::integer
  from jsonb_array_elements(changes) as change(value)
  where player.id = (change.value ->> 'playerId')::bigint;

  get diagnostics updated_count = row_count;
  if updated_count <> jsonb_array_length(changes) then
    raise exception 'player ranking update count mismatch';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'playerId', player.id,
    'nickname', player.nickname,
    'tier', player.tier,
    'order', player.tier_order
  ) order by player.id), '[]'::jsonb)
  into after_values
  from public.players as player
  join jsonb_array_elements(changes) as change(value)
    on player.id = (change.value ->> 'playerId')::bigint;

  insert into public.audit_logs (actor_id, actor_name, action, entity_type, before_data, after_data)
  values (
    p_actor_id,
    coalesce((select display_name from public.profiles where id = p_actor_id), '알 수 없음'),
    'players.rank.update',
    'player',
    before_values,
    after_values
  );
  return updated_count;
end;
$$;

revoke all on function public.set_player_tiers(jsonb, uuid) from public, anon, authenticated;
grant execute on function public.set_player_tiers(jsonb, uuid) to service_role;

create or replace function public.set_member_roles(changes jsonb, p_actor_id uuid)
returns integer
language plpgsql
set search_path = ''
as $$
declare
  before_values jsonb;
  after_values jsonb;
  updated_count integer;
begin
  select coalesce(jsonb_agg(jsonb_build_object(
    'userId', profile.id,
    'displayName', profile.display_name,
    'role', profile.role
  ) order by profile.id), '[]'::jsonb)
  into before_values
  from public.profiles as profile
  join jsonb_array_elements(changes) as change(value)
    on profile.id = (change.value ->> 'userId')::uuid
  where profile.role <> 'super_admin';

  if jsonb_array_length(before_values) <> jsonb_array_length(changes) then
    raise exception 'member role update count mismatch';
  end if;

  update public.profiles as profile
  set role = (change.value ->> 'role')::public.app_role
  from jsonb_array_elements(changes) as change(value)
  where profile.id = (change.value ->> 'userId')::uuid
    and profile.role <> 'super_admin';

  get diagnostics updated_count = row_count;
  if updated_count <> jsonb_array_length(changes) then
    raise exception 'member role update count mismatch';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'userId', profile.id,
    'displayName', profile.display_name,
    'role', profile.role
  ) order by profile.id), '[]'::jsonb)
  into after_values
  from public.profiles as profile
  join jsonb_array_elements(changes) as change(value)
    on profile.id = (change.value ->> 'userId')::uuid;

  insert into public.audit_logs (actor_id, actor_name, action, entity_type, before_data, after_data)
  values (
    p_actor_id,
    coalesce((select display_name from public.profiles where id = p_actor_id), '알 수 없음'),
    'members.role.update',
    'profile',
    before_values,
    after_values
  );
  return updated_count;
end;
$$;

revoke all on function public.set_member_roles(jsonb, uuid) from public, anon, authenticated;
grant execute on function public.set_member_roles(jsonb, uuid) to service_role;

create or replace function public.save_match_result(
  p_match_id bigint,
  p_played_at timestamptz,
  p_a_score smallint,
  p_b_score smallint,
  p_winner public.match_team,
  p_mvp_player_id bigint,
  p_actor_id uuid
)
returns void
language plpgsql
set search_path = ''
as $$
declare
  before_value jsonb;
  after_value jsonb;
  mvp_name text;
  participant_count integer;
begin
  if p_played_at is null or p_a_score is null or p_b_score is null or p_winner is null or p_a_score < 0 or p_b_score < 0 or p_a_score = p_b_score
    or (p_winner = 'A' and p_a_score < p_b_score) or (p_winner = 'B' and p_b_score < p_a_score) then
    raise exception 'invalid match result';
  end if;

  select jsonb_build_object(
    'status', status,
    'playedAt', played_at,
    'aScore', a_score,
    'bScore', b_score,
    'winner', winner,
    'mvpPlayerId', mvp_player_id
  )
  into before_value
  from public.matches
  where id = p_match_id
  for update;
  if not found then raise exception 'match not found'; end if;

  select count(*) into participant_count from public.match_players where match_id = p_match_id;
  if participant_count <> 10 then raise exception 'match must have 10 participants'; end if;

  select player.nickname into mvp_name
  from public.match_players as member
  join public.players as player on player.id = member.player_id
  where member.match_id = p_match_id and member.player_id = p_mvp_player_id;
  if not found then raise exception 'mvp must be a match participant'; end if;

  update public.matches
  set status = 'completed', played_at = p_played_at, a_score = p_a_score, b_score = p_b_score, winner = p_winner, mvp = mvp_name, mvp_player_id = p_mvp_player_id
  where id = p_match_id;

  perform public.recalculate_player_records();

  select jsonb_build_object(
    'status', status,
    'playedAt', played_at,
    'aScore', a_score,
    'bScore', b_score,
    'winner', winner,
    'mvpPlayerId', mvp_player_id
  )
  into after_value
  from public.matches
  where id = p_match_id;

  insert into public.audit_logs (actor_id, actor_name, action, entity_type, entity_id, before_data, after_data)
  values (
    p_actor_id,
    coalesce((select display_name from public.profiles where id = p_actor_id), '알 수 없음'),
    'matches.result.save',
    'match',
    p_match_id::text,
    before_value,
    after_value
  );
end;
$$;

revoke all on function public.save_match_result(bigint, timestamptz, smallint, smallint, public.match_team, bigint, uuid) from public, anon, authenticated;
grant execute on function public.save_match_result(bigint, timestamptz, smallint, smallint, public.match_team, bigint, uuid) to service_role;
