create type public.app_role as enum ('user', 'admin');
create type public.match_status as enum ('scheduled', 'completed');
create type public.match_team as enum ('A', 'B');

create table public.players (
  id bigint generated by default as identity primary key,
  nickname text not null unique,
  tier smallint not null check (tier between 1 and 4),
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  thumbnail_path text
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role public.app_role not null default 'user',
  player_id bigint unique references public.players(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.matches (
  id bigint generated by default as identity primary key,
  scheduled_at timestamptz not null,
  map text not null default '증강 칼바람 협곡',
  status public.match_status not null default 'scheduled',
  team_a text[] not null default '{}',
  team_b text[] not null default '{}',
  a_score smallint check (a_score is null or a_score >= 0),
  b_score smallint check (b_score is null or b_score >= 0),
  mvp text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.match_players (
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  team public.match_team not null,
  separated_group smallint,
  primary key (match_id, player_id)
);

create index players_tier_idx on public.players (tier);
create index matches_status_scheduled_at_idx on public.matches (status, scheduled_at desc);
create index profiles_player_id_idx on public.profiles (player_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.players enable row level security;
alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.match_players enable row level security;

create policy "players are publicly readable"
  on public.players for select
  to anon, authenticated
  using (true);

create policy "users can read their own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "matches are publicly readable"
  on public.matches for select
  to anon, authenticated
  using (true);

create policy "match players are publicly readable"
  on public.match_players for select
  to anon, authenticated
  using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'player-thumbnails',
  'player-thumbnails',
  true,
  3145728,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "player thumbnails are publicly readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'player-thumbnails');

insert into public.players (nickname, tier, wins, losses) values
  ('황금후라이드', 1, 18, 6),
  ('치킨무도사', 1, 15, 7),
  ('ARAMKING', 1, 12, 6),
  ('바삭한한타', 1, 11, 6),
  ('닭다리헌터', 2, 13, 9),
  ('매운양념', 2, 11, 9),
  ('무지성눈덩이', 2, 9, 8),
  ('증강수집가', 2, 10, 9),
  ('눈덩이배송', 2, 8, 8),
  ('부쉬속치킨', 3, 8, 10),
  ('포킹장인', 3, 7, 10),
  ('순살주의보', 3, 6, 11),
  ('닭날개', 3, 7, 12),
  ('부활대기중', 3, 5, 9),
  ('칼바람새싹', 4, 4, 10),
  ('튀김옷', 4, 3, 9),
  ('치즈볼', 4, 2, 8),
  ('무적포로', 4, 4, 12)
on conflict (nickname) do nothing;

insert into public.matches (
  scheduled_at, map, status, team_a, team_b, a_score, b_score, mvp
) values
  (
    '2026-07-24T12:00:00.000Z', '증강 칼바람 협곡', 'scheduled',
    array['황금후라이드', '무지성눈덩이', '포킹장인', '닭날개', '칼바람새싹'],
    array['치킨무도사', '닭다리헌터', '부쉬속치킨', '순살주의보', '치즈볼'],
    null, null, null
  ),
  (
    '2026-07-27T11:30:00.000Z', '증강 칼바람 협곡', 'scheduled',
    array['ARAMKING', '매운양념', '증강수집가', '부활대기중', '튀김옷'],
    array['바삭한한타', '눈덩이배송', '부쉬속치킨', '닭날개', '무적포로'],
    null, null, null
  ),
  (
    '2026-07-18T12:00:00.000Z', '증강 칼바람 협곡', 'completed',
    array['황금후라이드', '닭다리헌터', '포킹장인', '닭날개', '치즈볼'],
    array['치킨무도사', '매운양념', '부쉬속치킨', '순살주의보', '칼바람새싹'],
    2, 1, '황금후라이드'
  ),
  (
    '2026-07-15T11:30:00.000Z', '증강 칼바람 협곡', 'completed',
    array['ARAMKING', '무지성눈덩이', '증강수집가', '부활대기중', '무적포로'],
    array['바삭한한타', '닭다리헌터', '눈덩이배송', '순살주의보', '튀김옷'],
    0, 2, '치킨무도사'
  );
